config/routes.rb
Rails.application.routes.draw do
  resources :colors 
     resources :color_plates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :color_plates, inverse_of: :color
    accepts_nested_attributes_for :color_plates, allow_destroy: true, reject_if: :all_blank
end

app/models/color_plate.rb
class ColorPlate < ApplicationRecord
    belongs_to :color
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/color_plates_controller.rb
class ColorPlatesController < ApplicationController
    before_action :set_color_plate, only: [:show, :edit, :update, :destroy]
    
    def index
      @color_plates = ColorPlate.all
    end

    def show
    end

    def edit
    end

    def new
      @color_plate = ColorPlate.new
    end

    def create
      @color_plate = ColorPlate.new(color_plate_params)
  
      if @color_plate.save
        redirect_to @color_plate
      else
        redirect_to @color_plate
      end
    end
  
    def destroy
      @color_plate.destroy
      redirect_to color_path(@color)
    end
  
    def update
      respond_to do |format|
        if @color_plate.update(color_plate_params)
          format.html { redirect_to color_url(@color), notice: 'color has been updated' }
        else
          format.html { redirect_to color_url(@color), alert: 'color was not updated!' }
        end
      end
    end
  
    private
  
    def set_color_plate
      @color_plate = ColorPlate.find(params[:id])
    end
  
    def color_plate_params
      params.require(:color_plate).permit(:color_name, :color_code, :color_pik, :color_id)
    end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
    before_action :set_before, only: [ :edit, :show, :update, :destroy]

    def index
       @colors = Color.all
    end

    def new
       @color = Color.new
    end

    def edit 
    end

    def show
    end

    def create
       @color = Color.new(params_color)
       if @color.save
        redirect_to @color
       else
        render :new
       end
    end

    def update
       if @color.update(params_color)
        redirect_to @color 
       else 
        render :edit
       end
    end

    def destroy
        @color.destroy
        redirect_to @color   
    end 

    private 

    def set_before
       @color = Color.find(params[:id])
    end

    def params_color
       params.require(:color).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/color_plates_helper.rb
module ColorPlatesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/color_plates/_color_plate.html.erb
<%= turbo_frame_tag color_plate do %>
    <div class="color_plate">
      <%= link_to color_plate.color_name, 
                  color_plate_path(quote),
                  data: { turbo_frame: "_top"} %>
      <div class="color_plate__actions">
        <%= button_to "Delete",
                      color_plate_path(color_plate),
                      method: :delete,
                      class: "btn btn--light" %>
        <%= link_to "Edit",
                    edit_color_plate_path(color_plate),
                    class: "btn btn--light" %>
      </div>
    </div>
<% end %>

app/views/color_plates/_form.html.erb
<div class="container mx-auto pt-5">
  <%= form_with(model: @color_plate , data: { controller: "color-picker" } ) do |f| %>
    <div class="my-5">
      <h1 class=" text-2xl text-blue-500"><%= f.label :color_name %></h1>
      <p ><%= f.text_field :color_name %></p>
    </div>  
    
    <div class="my-5">
      <h1 class=" text-2xl text-blue-500"><%= f.label :color %></h1> 
      <%= color_field_tag(:div, "", class:"picker", data: {
      color_picker_target: "picker"
      }) %>
    </div>
    
    <div class="my-5">
    <p><%= f.submit "Add Color" %></p>
    </div>
    <br/>
    <button class=" bg-blue-500 ">
          Button
    </button>

    <br/>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
          Button
    </button>
  <% end %>
</div>  

app/views/color_plates/index.html.erb
<main class="container">
<div class="header">
  <h1>Color</h1>
  <%= link_to "New color",
            new_color_plate_path,
            class: "btn btn--primary", 
            data: { turbo_frame: dom_id(ColorPlate.new) } %>
</div>
<%= turbo_frame_tag ColorPlate.new %>

<%= turbo_frame_tag "color_plates" do %>
  <%= render @color_plates %>
<% end %>  
</main>

app/views/color_plates/new.html.erb
<%= render "form" %>

app/views/color_plates/show.html.erb
<%= @color_plate.color_name %>

<%= @color_plate.color_code %>

<%= @color_plate.color_pik %>

app/views/colors/_form.html.erb
<%= form_with(model: @color) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/colors/edit.html.erb
<h1> edit color <h1>

<%= render "form" %>

<%= link_to "back", colors_path  %>

app/views/colors/index.html.erb
<h1> This is a color <h1>

<table>
   <thead>
      <th>Name<th>
   <thead>
   <tbody>
      <% @colors.each do |color| %>
      <tr>
       <td><%= color.name %></td>
       <td><%= link_to "show", color_path(color) %></td>
       <td><%= link_to "edit", edit_color_path(color) %></td>
       <td><%= button_to "destroy", color, method: :delete %>
       </tr>
       <% end %>
    </tbody>   
       <br/>
</table>
       <%= link_to "add color", new_color_path %>

app/views/colors/new.html.erb
<h1> new color <h1>

<%= render "form" %>

app/views/colors/show.html.erb
<%= @color.name %>
<%= link_to "Edit", edit_color_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorPicker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>